### ISSUE TITLE
Add config option for 1:1 ore processing

### ISSUE THREAD

**Issue by sihawken** [Drullkus/ThermalSmeltery#10]
I've turned off 1:2 ore processing in all mods so far, including Tinkers Construct and Tinkers Steelworks.

Would it be possible to add a config to set the ratio or ores to ingots?

**Comment by Drullkus** [comment]
Thermal Smeltery copies all of the TiCon Smeltery recipes. If you set it to 1:1 in TCon it will be 1:1 in the Magma Crucible as well.

**Comment by sihawken** [comment]
Facepalm. I thought I changed it already. Thanks
