### ISSUE TITLE
Client Crash with Tinkers' Armor

### ISSUE THREAD

**Issue by GeoTerra** [Drullkus/ThermalSmeltery#11]
Got this crash when I tried to place the "Adventurer's Glove" item into the Tool Forge, Tool Station, or Crafting Station in an attempt to add modifiers: http://pastebin.com/FH1HuQhs

It would seem that this issue isn't isolated as "kikisp" on the mod's Curse page linked the same crash.

It should be noted that after I reenter the world where I crashed, the Glove item is gone. It's not in any of the tables, nor in my inventory. I have not tested with any of the other Adventurer armor items as of yet.

If any additional details are required, please do let me know.

**Comment by JasonB42** [comment]
Also having this problem with TravelWings: http://pastebin.com/PevEWriY

Was this already fixed by https://github.com/alexbegt with: https://github.com/Drullkus/ThermalSmeltery/commit/085d1b14756e363ff806747d584b3c3f0b680431 ?

**Comment by Drullkus** [comment]
Yes it is fixed by Alexbegt

**Comment by Drullkus** [comment]
Fixed in Thermal Smeltery Version 1.1.2
