### ISSUE TITLE
Thermal Smeltery Machines

### ISSUE THREAD

**Issue by Drullkus** [Drullkus/ThermalSmeltery#19]
Issue made as per @hilburn's request.
- [x] Augments
- [ ] Recipes
- [ ] Finding a tester

**Comment by hilburn** [comment]
bahhhhh recipes, what kind of nerd needs recipes?
by augments do you just mean default augments (redstone, sides and the other one)?

**Comment by Drullkus** [comment]
Yeah, when the machines are placed, they seem to be missing augments. When I place the machines too, they automatically get the owner tab (It's gray?)

**Comment by hilburn** [comment]
ok, should be easy enough to fix i think
