### ISSUE TITLE
Fixes before releasing 1.3.0

### ISSUE THREAD

**Issue by Drullkus** [Drullkus/ThermalSmeltery#21]
- [x] Fix the ! problem in the GUI interface for Autocaster
- [ ] Fix the EnderIO Module not activating
- [x] Fix the servo augment not being given in new versions of TE
- [x] Add Recipes

**Comment by hilburn** [comment]
care to elaborate on the issues or are you handling them?

**Comment by Drullkus** [comment]
I'll handle the recipes and the EnderIO module. 

The ! problem is referring to [this](https://github.com/Drullkus/ThermalSmeltery/blob/hilburnMachines/src/main/java/com/drullkus/thermalsmeltery/common/gui/client/GuiExtruder.java#L120) which may be why the AutoCaster might be not well-responsive in the GUI when you hit that button to switch casting mode. (Blocks/Ingots)

If you re-ran the gradle to re-dl deps, I updated them. For some reason, the machines, when placed, don't have the Servo augment like the TE machines do. They can't push items to a target inventory block either.

**Comment by hilburn** [comment]
I'll have a look when I can - I might be able to do it tonight, depends how work goes (on a business trip atm)

**Comment by Drullkus** [comment]
@hilburn Fixes? :(

**Comment by hilburn** [comment]
Do you actually test build files before pushing them? this is what `gradlew setupdecompworkspace idea --refresh-dependencies` just did to my dev environment:

![](http://puu.sh/k1BLv/c6b88d9bc9.png)

**Comment by hilburn** [comment]
Autocaster issue is not actually an issue - it changes instantly when nothing is being processed, but if you are already working on something and try to change it, it outputs that before changing the mode.

**Comment by Drullkus** [comment]
Weird, I never got that error a few weeks ago﻿ D':

Will test later
