### ISSUE TITLE
TiCon/yellorium liquid amount

### ISSUE THREAD

**Issue by bochen415** [Drullkus/ThermalSmeltery#24]
When leaving the smelt yellorium option set to true (default) the amount of fluid needed to cast an ingot/block is incorrect.
When the option is set to false and AOBD handles that (I think) the amount works as expected.

[pic related](http://i.imgur.com/UOk4y8T.png)

ThermalSmeltery-1.7.10-1.2.1
AOBD-2.8.4
TConstruct-1.7.10-1.8.8
Forge 1588

**Comment by Drullkus** [comment]
Oh, blah. Looks like I'll need to fix this.
