### ISSUE TITLE
Where are the bug reports? 

### ISSUE THREAD

**Issue by Holladiewal** [Drullkus/ThermalSmeltery#26]
I don't know what you did but there are like no bug reports in the last 5+ month. CONGRATULATIONS!!!!

**Comment by alexbegt** [comment]
BUG REPORT: THIS MOD CRASHED ME TO MY XBOX LOGO!

**Comment by Holladiewal** [comment]
What is an Xbox logo?

**Comment by alexbegt** [comment]
@beepbeat It was a joke for @Drullkus :P

**Comment by Drullkus** [comment]
What's a joke? :P
