### ISSUE TITLE
Crash on startup [MC 1.10.2]

### ISSUE THREAD

**Issue by KristjanKr** [Drullkus/ThermalSmeltery#31]
Game crashes on startup with following crash log:

https://paste.ee/p/5keJU

Forge build:1.10.2-12.18.3.2254
Thermal Smeltery build:ThermalSmeltery-1.10.2-2.0.0.jar
Minecraft 1.10.2

**Comment by vrork** [comment]
Crash here too
http://pastebin.com/muxMHSVp

**Comment by 0Navis0** [comment]
I get the same crash too http://pastebin.com/hxcQVcQM

**Comment by heidrifx** [comment]
Same here: http://pastebin.com/ihiVzis9
Would be really cool if this gets fixed soon because the mod itself looks pretty interesting ;)

**Comment by Landmaster** [comment]
see my pull request (#32) for a possible fix

**Comment by 0Navis0** [comment]
The crash still happens with the new version. :( http://pastebin.com/QuzqpLCG

**Comment by Drullkus** [comment]
Bloody heck, I'll get a nullcheck written. What modpack? FTB Beyond runs like a sail with TSmelt.

**Comment by 0Navis0** [comment]
My own modpack ULTRA.

**Comment by Landmaster** [comment]
@Hypsellis The new crash that you are still getting is most likely not related to the original crash that you were getting, looking at the crash reports.

@Drullkus I have just added in another required null check (which is different from the first null check that I added) in my pull request #32. For some reason my original fix worked fine with my mods, but somehow it seems that a null item has most likely wound up as a smeltery input in the ULTRA modpack -_-

**Comment by 0Navis0** [comment]
Thanks for the fix, I don't get more crash. ;)

**Comment by Landmaster** [comment]
So there were even more thingumajigs causing the crash than I thought, rendering #32 obsolete (I have closed it already). Ha. -_- xD
