### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by a-frenzy** [Drullkus/ThermalSmeltery#33]
https://gist.github.com/frenzye/05e44b0aabae0ca583e3f6a43941f669

**Comment by dshadowwolf** [comment]
Can confirm. NPE in "us.drullk.thermalsmeltery.common.Compat.letsGetCooking" at line 20 - which, in the current code, is a brace.

**Comment by MokahTGS** [comment]
Confirmed.  Here's my log:

This is on the 2.0.1 version.

http://pastebin.com/ZEUSEGLb

**Comment by Drullkus** [comment]
Update to latest 2.0.2 please
